flink:
  kafka:
    deliveryGuarantee: "EXACTLY_ONCE"
    producer:
      bootstrap:
        servers: "10.20.32.53:9092"
      topic: "flink-kafka-topic"
      transaction:
        timeout:
          ms: 900000
        max:
          timeout:
            ms: 900000
    consumer:
      bootstrap:
        servers: "10.20.32.53:9092"
      group:
        id: "flink-kafka-group"
      topic: "flink-kafka-topic"