flink:
  app:
    appName: flink-kafka-data-mock
    flinkConfig:
      # flink 地址
      url: http://172.16.0.232:8082/
      # flink job jar 的名称
      jarName: pipeline-job-demo-data-mock-processor-core-0.0.1-SNAPSHOT-jar-with-dependencies.jar
      # 目前仅支持standalone
      mode: standalone
      # 并行度
      parallelism: 2