flink:
  pipeline:
    pluginPackages: com.zj.flink.plugin
    pipelineName: dataSensitiveScanPipeline
    disableChaining: true
    pipeline:
      input: kafkaInputPipelinePlugin
      output: printOutputPipelinePlugin
      plugins:
        - hostnameFilterPipelinePlugin
        - dataSensitiveScanPipelinePlugin
        - riskScanPipelinePlugin