flink:
  pipeline:
    pluginPackages: com.zj.flink.plugin
    pipelines:
      kafkaDataSensitiveScanPipeline:
        input: kafkaInputPipelinePlugin
        output: printOutputPipelinePlugin
        plugins:
          - hostnameFilterPipelinePlugin
          - dataSensitiveScanPipelinePlugin
          - riskScanPipelinePlugin